name:         hackage-db
version:      "2.0"
synopsis:     Access Hackage's package database via Data.Map
category:     Distribution
author:       Peter Simons, Alexander Altman, Ben James
maintainer:   Peter Simons <simons@cryp.to>
github:       peti/hackage-db
license:      BSD3
tested-with:  GHC > 7.8 && < 8.3
description:  !
  This is an early and mostly undocumented release of the 2.x version of
  hackage-db that's intended mostly for experimenting with and testing of the
  new API. Porting code from 1.x to 2.x is pretty simple, but if you do that at
  this point, please expect minor details of this API to change in forthcoming
  releases. For production code, you are probably better off with the 1.x
  release for now.

  .

  Check out https://github.com/peti/hackage-db/tree/master/example/ for a
  collection of simple example programs that demonstrate how to use this code.

dependencies:
  - base >= 3 && < 5
  - Cabal
  - containers

library:
  source-dirs: src
  exposed-modules:
    - Distribution.Hackage.DB
    - Distribution.Hackage.DB.Errors
    - Distribution.Hackage.DB.MetaData
    - Distribution.Hackage.DB.Parsed
    - Distribution.Hackage.DB.Path
    - Distribution.Hackage.DB.Unparsed
    - Distribution.Hackage.DB.Utility
  dependencies:
    - aeson
    - bytestring
    - directory
    - filepath
    - tar >= 0.4
    - time
    - utf8-string
  other-extensions:
    - DeriveDataTypeable
    - DeriveGeneric

executables:
  list-known-versions:
    main:               list-known-versions.hs
    source-dirs:        example
    dependencies:
      - hackage-db
      - bytestring

  show-meta-data:
    main:               show-meta-data.hs
    source-dirs:        example
    dependencies:
      - hackage-db
      - bytestring
      - utf8-string

  show-package-versions:
    main:               show-package-versions.hs
    source-dirs:        example
    dependencies:
      - hackage-db
